### ISSUE TITLE
Question about the linear motion modification

### ISSUE THREAD

**Issue by coroner4817** [vrtsig/costMatLinearGuidedTracks#1]
Hi Fabian,

I just wondering, in the uTrack, if we already use Kalman filter to track the trajectory, are we suppose to think it is a linear motion tracker? Since Kalman filter handles with linear systems.

I think the propagation scheme already include the linear motion schemes (the information of the speed). So do we still need to add the angle penalty into the costMat? 

I am doing a similar linear tracking project so just wondering whether I need to modify the uTrack? BTW, how good is your modification's performance in comparison with the original uTrack? Thanks!

Yingnan

**Comment by vrtsig** [comment]
Hi Yingnan.

You are right: the original uTrack supports a mix of linear and Brownian motion and does propagate positions via a kalman filter. It thens look for a potential connection near the propagated position. However, in practise I found that because of the relatively large range of speeds I needed to cover, the resulting tracks were incredibly zig-zaggy and completely unusable for my application. This problem gets worse if you have to deal with the appearance and disappearance of particles, e.g. due to optical focus issues. Also, because the algorithm is locally greedy, the construction of a track often succeeds or fails based on the first connection that is established - which is why I limit these. Since axonal transport is essentially 'on rails' I found that the angle criterion helped a lot.

uTrack itself doesn't need to be changed; you just have to tell it to use the cost matrices.

If you want to have a look at a similar (and far more thoroughly reviewed) project comparable to this here, I suggest you have a look at TrackMate for Fiji / ImageJ and its source code. It is based on uTrack, too and includes cost matrices for linear propagation.

Whatever you do I highly suggest you check your results against manual tracking. It's soul destroying work but ultimately I think it'll tell you what solution to use.

Hope this helps.

Fabian

**Comment by coroner4817** [comment]
Hi Fabian,

Thank you very much for your detailed answer. I will figure out what is best for my case 😀

Yingnan
